parameters:
    database_host: mysql
    database_port: 3306
    database_name: "%env(MYSQL_DATABASE)%"
    database_user: "%env(MYSQL_USER)%"
    database_password: "%env(MYSQL_PASSWORD)%"
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
