neo_list_hazardous:
    path:     /hazardous
    defaults: { _controller: NeoBundle:Asteroid:getHazardous }

neo_list_fastest:
    path:     /fastest
    defaults: { _controller: NeoBundle:Asteroid:getFastest }

neo_list_bestyear:
    path:     /best-year
    defaults: { _controller: NeoBundle:Asteroid:getBestYear }

neo_list_bestmonth:
    path:     /best-month
    defaults: { _controller: NeoBundle:Asteroid:getBestMonth }
